// auto generated by Marsh v0.1.0
// do not edit this file manually

use chrono::{DateTime, Utc};
use uuid::Uuid;

pub struct User {
    pub id: Uuid,
    pub username: String,
    pub email: String,
    pub hashed_password: String,
}

pub struct SessionToken {
    pub id: Uuid,
    pub user_id: Uuid,
    pub created_at: DateTime<Utc>,
    pub expiration: DateTime<Utc>,
}

