DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS session_tokens CASCADE;
DROP TABLE IF EXISTS songs CASCADE;
DROP TYPE IF EXISTS familiarity_level CASCADE;
DROP TABLE IF EXISTS user_songs CASCADE;
